FROM python:3.10-slim

RUN pip install --no-cache-dir --timeout=300 --retries=5 mlflow==2.13.0

WORKDIR /mlflow

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "/mlflow/mlruns", \
     "--artifacts-destination", "./mlruns", \
     "--serve-artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]